spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema-h2.sql
      data-locations: classpath:sql/data-h2.sql
      username: sa
      password: sa
  main:
    banner-mode: off
