/*
 * This file is generated by jOOQ.
 */
package alex.jooq.tables;

import alex.jooq.Indexes;
import alex.jooq.Keys;
import alex.jooq.Test;
import alex.jooq.tables.records.PersonRecord;
import java.util.Arrays;
import java.util.List;
import jakarta.annotation.Generated;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@Generated(
        value = {"http://www.jooq.org", "jOOQ version:3.10.7"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Person extends TableImpl<PersonRecord> {

    private static final long serialVersionUID = 361651853;

    /** The reference instance of <code>test.person</code> */
    public static final Person PERSON = new Person();

    /** The class holding records for this type */
    @Override
    public Class<PersonRecord> getRecordType() {
        return PersonRecord.class;
    }

    /** The column <code>test.person.id</code>. */
    public final TableField<PersonRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /** The column <code>test.person.name</code>. */
    public final TableField<PersonRecord, String> NAME =
            createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /** The column <code>test.person.address</code>. */
    public final TableField<PersonRecord, String> ADDRESS =
            createField("address", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /** The column <code>test.person.age</code>. */
    public final TableField<PersonRecord, Integer> AGE =
            createField("age", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /** Create a <code>test.person</code> table reference */
    public Person() {
        this(DSL.name("person"), null);
    }

    /** Create an aliased <code>test.person</code> table reference */
    public Person(String alias) {
        this(DSL.name(alias), PERSON);
    }

    /** Create an aliased <code>test.person</code> table reference */
    public Person(Name alias) {
        this(alias, PERSON);
    }

    private Person(Name alias, Table<PersonRecord> aliased) {
        this(alias, aliased, null);
    }

    private Person(Name alias, Table<PersonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /** {@inheritDoc} */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /** {@inheritDoc} */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PERSON_PRIMARY);
    }

    /** {@inheritDoc} */
    @Override
    public Identity<PersonRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PERSON;
    }

    /** {@inheritDoc} */
    @Override
    public UniqueKey<PersonRecord> getPrimaryKey() {
        return Keys.KEY_PERSON_PRIMARY;
    }

    /** {@inheritDoc} */
    @Override
    public List<UniqueKey<PersonRecord>> getKeys() {
        return Arrays.<UniqueKey<PersonRecord>>asList(Keys.KEY_PERSON_PRIMARY);
    }

    /** {@inheritDoc} */
    @Override
    public Person as(String alias) {
        return new Person(DSL.name(alias), this);
    }

    /** {@inheritDoc} */
    @Override
    public Person as(Name alias) {
        return new Person(alias, this);
    }

    /** Rename this table */
    @Override
    public Person rename(String name) {
        return new Person(DSL.name(name), null);
    }

    /** Rename this table */
    @Override
    public Person rename(Name name) {
        return new Person(name, null);
    }
}
