package alex.dto;

public class School {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testdb.public.school.id
     *
     * @mbg.generated Sun Nov 26 21:15:27 GST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testdb.public.school.name
     *
     * @mbg.generated Sun Nov 26 21:15:27 GST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testdb.public.school.id
     *
     * @return the value of testdb.public.school.id
     *
     * @mbg.generated Sun Nov 26 21:15:27 GST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testdb.public.school
     *
     * @mbg.generated Sun Nov 26 21:15:27 GST 2023
     */
    public School withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testdb.public.school.id
     *
     * @param id the value for testdb.public.school.id
     *
     * @mbg.generated Sun Nov 26 21:15:27 GST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testdb.public.school.name
     *
     * @return the value of testdb.public.school.name
     *
     * @mbg.generated Sun Nov 26 21:15:27 GST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testdb.public.school
     *
     * @mbg.generated Sun Nov 26 21:15:27 GST 2023
     */
    public School withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testdb.public.school.name
     *
     * @param name the value for testdb.public.school.name
     *
     * @mbg.generated Sun Nov 26 21:15:27 GST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testdb.public.school
     *
     * @mbg.generated Sun Nov 26 21:15:27 GST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}