package com.example.springbootredis;

public class SysDict {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_dict.id
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_dict.parent_id
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_dict.code
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_dict.name
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_dict.value
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_dict.seq
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_dict.has_child
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    private Boolean hasChild;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_dict.enabled
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_dict.id
     *
     * @return the value of sys_dict.id
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * sys_dict
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public SysDict withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_dict.id
     *
     * @param id the value for sys_dict.id
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_dict.parent_id
     *
     * @return the value of sys_dict.parent_id
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * sys_dict
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public SysDict withParentId(Integer parentId) {
        this.setParentId(parentId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_dict.parent_id
     *
     * @param parentId the value for sys_dict.parent_id
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_dict.code
     *
     * @return the value of sys_dict.code
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * sys_dict
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public SysDict withCode(String code) {
        this.setCode(code);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_dict.code
     *
     * @param code the value for sys_dict.code
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_dict.name
     *
     * @return the value of sys_dict.name
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * sys_dict
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public SysDict withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_dict.name
     *
     * @param name the value for sys_dict.name
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_dict.value
     *
     * @return the value of sys_dict.value
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * sys_dict
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public SysDict withValue(String value) {
        this.setValue(value);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_dict.value
     *
     * @param value the value for sys_dict.value
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_dict.seq
     *
     * @return the value of sys_dict.seq
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * sys_dict
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public SysDict withSeq(Integer seq) {
        this.setSeq(seq);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_dict.seq
     *
     * @param seq the value for sys_dict.seq
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_dict.has_child
     *
     * @return the value of sys_dict.has_child
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public Boolean getHasChild() {
        return hasChild;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * sys_dict
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public SysDict withHasChild(Boolean hasChild) {
        this.setHasChild(hasChild);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_dict.has_child
     *
     * @param hasChild the value for sys_dict.has_child
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public void setHasChild(Boolean hasChild) {
        this.hasChild = hasChild;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_dict.enabled
     *
     * @return the value of sys_dict.enabled
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * sys_dict
     *
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public SysDict withEnabled(Boolean enabled) {
        this.setEnabled(enabled);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_dict.enabled
     *
     * @param enabled the value for sys_dict.enabled
     * @mbg.generated Fri Aug 11 11:24:39 CST 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public String toString() {
        return "SysDict{"
                + "id="
                + id
                + ", parentId="
                + parentId
                + ", code='"
                + code
                + '\''
                + ", name='"
                + name
                + '\''
                + ", value='"
                + value
                + '\''
                + ", seq="
                + seq
                + ", hasChild="
                + hasChild
                + ", enabled="
                + enabled
                + '}';
    }
}
