CREATE TABLE PERSON (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(255) NOT NULL,
  last_name  VARCHAR(255) NOT NULL
);

CREATE sequence person_sequence START WITH 1 increment BY 1;

INSERT INTO PERSON (first_name, last_name) VALUES ('Dave', 'Syer');