/*
 * This file is generated by jOOQ.
*/
package alex.jooq;


import alex.jooq.tables.Customer;
import alex.jooq.tables.Person;
import alex.jooq.tables.QrtzBlobTriggers;
import alex.jooq.tables.QrtzCalendars;
import alex.jooq.tables.QrtzCronTriggers;
import alex.jooq.tables.QrtzFiredTriggers;
import alex.jooq.tables.QrtzJobDetails;
import alex.jooq.tables.QrtzLocks;
import alex.jooq.tables.QrtzPausedTriggerGrps;
import alex.jooq.tables.QrtzSchedulerState;
import alex.jooq.tables.QrtzSimpleTriggers;
import alex.jooq.tables.QrtzSimpropTriggers;
import alex.jooq.tables.QrtzTriggers;
import alex.jooq.tables.School;
import javax.annotation.Generated;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUSTOMER_PRIMARY = Indexes0.CUSTOMER_PRIMARY;
    public static final Index PERSON_PRIMARY = Indexes0.PERSON_PRIMARY;
    public static final Index QRTZ_BLOB_TRIGGERS_PRIMARY = Indexes0.QRTZ_BLOB_TRIGGERS_PRIMARY;
    public static final Index QRTZ_BLOB_TRIGGERS_SCHED_NAME = Indexes0.QRTZ_BLOB_TRIGGERS_SCHED_NAME;
    public static final Index QRTZ_CALENDARS_PRIMARY = Indexes0.QRTZ_CALENDARS_PRIMARY;
    public static final Index QRTZ_CRON_TRIGGERS_PRIMARY = Indexes0.QRTZ_CRON_TRIGGERS_PRIMARY;
    public static final Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_INST_JOB_REQ_RCVRY = Indexes0.QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_INST_JOB_REQ_RCVRY;
    public static final Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_JG = Indexes0.QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_JG;
    public static final Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_J_G = Indexes0.QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_J_G;
    public static final Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_TG = Indexes0.QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_TG;
    public static final Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_TRIG_INST_NAME = Indexes0.QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_TRIG_INST_NAME;
    public static final Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_T_G = Indexes0.QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_T_G;
    public static final Index QRTZ_FIRED_TRIGGERS_PRIMARY = Indexes0.QRTZ_FIRED_TRIGGERS_PRIMARY;
    public static final Index QRTZ_JOB_DETAILS_IDX_QRTZ_J_GRP = Indexes0.QRTZ_JOB_DETAILS_IDX_QRTZ_J_GRP;
    public static final Index QRTZ_JOB_DETAILS_IDX_QRTZ_J_REQ_RECOVERY = Indexes0.QRTZ_JOB_DETAILS_IDX_QRTZ_J_REQ_RECOVERY;
    public static final Index QRTZ_JOB_DETAILS_PRIMARY = Indexes0.QRTZ_JOB_DETAILS_PRIMARY;
    public static final Index QRTZ_LOCKS_PRIMARY = Indexes0.QRTZ_LOCKS_PRIMARY;
    public static final Index QRTZ_PAUSED_TRIGGER_GRPS_PRIMARY = Indexes0.QRTZ_PAUSED_TRIGGER_GRPS_PRIMARY;
    public static final Index QRTZ_SCHEDULER_STATE_PRIMARY = Indexes0.QRTZ_SCHEDULER_STATE_PRIMARY;
    public static final Index QRTZ_SIMPLE_TRIGGERS_PRIMARY = Indexes0.QRTZ_SIMPLE_TRIGGERS_PRIMARY;
    public static final Index QRTZ_SIMPROP_TRIGGERS_PRIMARY = Indexes0.QRTZ_SIMPROP_TRIGGERS_PRIMARY;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_C = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_C;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_G = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_G;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_J = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_J;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_JG = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_JG;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_NEXT_FIRE_TIME = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_NEXT_FIRE_TIME;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_MISFIRE = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_MISFIRE;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST_MISFIRE = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST_MISFIRE;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST_MISFIRE_GRP = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST_MISFIRE_GRP;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_N_G_STATE = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_N_G_STATE;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_N_STATE = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_N_STATE;
    public static final Index QRTZ_TRIGGERS_IDX_QRTZ_T_STATE = Indexes0.QRTZ_TRIGGERS_IDX_QRTZ_T_STATE;
    public static final Index QRTZ_TRIGGERS_PRIMARY = Indexes0.QRTZ_TRIGGERS_PRIMARY;
    public static final Index SCHOOL_PRIMARY = Indexes0.SCHOOL_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CUSTOMER_PRIMARY = Internal.createIndex("PRIMARY", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index PERSON_PRIMARY = Internal.createIndex("PRIMARY", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
        public static Index QRTZ_BLOB_TRIGGERS_PRIMARY = Internal.createIndex("PRIMARY", QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS, new OrderField[] { QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.SCHED_NAME, QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_NAME, QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP }, true);
        public static Index QRTZ_BLOB_TRIGGERS_SCHED_NAME = Internal.createIndex("SCHED_NAME", QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS, new OrderField[] { QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.SCHED_NAME, QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_NAME, QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP }, false);
        public static Index QRTZ_CALENDARS_PRIMARY = Internal.createIndex("PRIMARY", QrtzCalendars.QRTZ_CALENDARS, new OrderField[] { QrtzCalendars.QRTZ_CALENDARS.SCHED_NAME, QrtzCalendars.QRTZ_CALENDARS.CALENDAR_NAME }, true);
        public static Index QRTZ_CRON_TRIGGERS_PRIMARY = Internal.createIndex("PRIMARY", QrtzCronTriggers.QRTZ_CRON_TRIGGERS, new OrderField[] { QrtzCronTriggers.QRTZ_CRON_TRIGGERS.SCHED_NAME, QrtzCronTriggers.QRTZ_CRON_TRIGGERS.TRIGGER_NAME, QrtzCronTriggers.QRTZ_CRON_TRIGGERS.TRIGGER_GROUP }, true);
        public static Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_INST_JOB_REQ_RCVRY = Internal.createIndex("IDX_QRTZ_FT_INST_JOB_REQ_RCVRY", QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS, new OrderField[] { QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.SCHED_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.INSTANCE_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.REQUESTS_RECOVERY }, false);
        public static Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_JG = Internal.createIndex("IDX_QRTZ_FT_JG", QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS, new OrderField[] { QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.SCHED_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.JOB_GROUP }, false);
        public static Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_J_G = Internal.createIndex("IDX_QRTZ_FT_J_G", QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS, new OrderField[] { QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.SCHED_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.JOB_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.JOB_GROUP }, false);
        public static Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_TG = Internal.createIndex("IDX_QRTZ_FT_TG", QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS, new OrderField[] { QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.SCHED_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP }, false);
        public static Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_TRIG_INST_NAME = Internal.createIndex("IDX_QRTZ_FT_TRIG_INST_NAME", QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS, new OrderField[] { QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.SCHED_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.INSTANCE_NAME }, false);
        public static Index QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_T_G = Internal.createIndex("IDX_QRTZ_FT_T_G", QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS, new OrderField[] { QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.SCHED_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.TRIGGER_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP }, false);
        public static Index QRTZ_FIRED_TRIGGERS_PRIMARY = Internal.createIndex("PRIMARY", QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS, new OrderField[] { QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.SCHED_NAME, QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS.ENTRY_ID }, true);
        public static Index QRTZ_JOB_DETAILS_IDX_QRTZ_J_GRP = Internal.createIndex("IDX_QRTZ_J_GRP", QrtzJobDetails.QRTZ_JOB_DETAILS, new OrderField[] { QrtzJobDetails.QRTZ_JOB_DETAILS.SCHED_NAME, QrtzJobDetails.QRTZ_JOB_DETAILS.JOB_GROUP }, false);
        public static Index QRTZ_JOB_DETAILS_IDX_QRTZ_J_REQ_RECOVERY = Internal.createIndex("IDX_QRTZ_J_REQ_RECOVERY", QrtzJobDetails.QRTZ_JOB_DETAILS, new OrderField[] { QrtzJobDetails.QRTZ_JOB_DETAILS.SCHED_NAME, QrtzJobDetails.QRTZ_JOB_DETAILS.REQUESTS_RECOVERY }, false);
        public static Index QRTZ_JOB_DETAILS_PRIMARY = Internal.createIndex("PRIMARY", QrtzJobDetails.QRTZ_JOB_DETAILS, new OrderField[] { QrtzJobDetails.QRTZ_JOB_DETAILS.SCHED_NAME, QrtzJobDetails.QRTZ_JOB_DETAILS.JOB_NAME, QrtzJobDetails.QRTZ_JOB_DETAILS.JOB_GROUP }, true);
        public static Index QRTZ_LOCKS_PRIMARY = Internal.createIndex("PRIMARY", QrtzLocks.QRTZ_LOCKS, new OrderField[] { QrtzLocks.QRTZ_LOCKS.SCHED_NAME, QrtzLocks.QRTZ_LOCKS.LOCK_NAME }, true);
        public static Index QRTZ_PAUSED_TRIGGER_GRPS_PRIMARY = Internal.createIndex("PRIMARY", QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS, new OrderField[] { QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME, QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP }, true);
        public static Index QRTZ_SCHEDULER_STATE_PRIMARY = Internal.createIndex("PRIMARY", QrtzSchedulerState.QRTZ_SCHEDULER_STATE, new OrderField[] { QrtzSchedulerState.QRTZ_SCHEDULER_STATE.SCHED_NAME, QrtzSchedulerState.QRTZ_SCHEDULER_STATE.INSTANCE_NAME }, true);
        public static Index QRTZ_SIMPLE_TRIGGERS_PRIMARY = Internal.createIndex("PRIMARY", QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS, new OrderField[] { QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS.SCHED_NAME, QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME, QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP }, true);
        public static Index QRTZ_SIMPROP_TRIGGERS_PRIMARY = Internal.createIndex("PRIMARY", QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS, new OrderField[] { QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.SCHED_NAME, QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.TRIGGER_NAME, QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.TRIGGER_GROUP }, true);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_C = Internal.createIndex("IDX_QRTZ_T_C", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.CALENDAR_NAME }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_G = Internal.createIndex("IDX_QRTZ_T_G", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_GROUP }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_J = Internal.createIndex("IDX_QRTZ_T_J", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.JOB_NAME, QrtzTriggers.QRTZ_TRIGGERS.JOB_GROUP }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_JG = Internal.createIndex("IDX_QRTZ_T_JG", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.JOB_GROUP }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_NEXT_FIRE_TIME = Internal.createIndex("IDX_QRTZ_T_NEXT_FIRE_TIME", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.NEXT_FIRE_TIME }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_MISFIRE = Internal.createIndex("IDX_QRTZ_T_NFT_MISFIRE", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.MISFIRE_INSTR, QrtzTriggers.QRTZ_TRIGGERS.NEXT_FIRE_TIME }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST = Internal.createIndex("IDX_QRTZ_T_NFT_ST", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_STATE, QrtzTriggers.QRTZ_TRIGGERS.NEXT_FIRE_TIME }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST_MISFIRE = Internal.createIndex("IDX_QRTZ_T_NFT_ST_MISFIRE", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.MISFIRE_INSTR, QrtzTriggers.QRTZ_TRIGGERS.NEXT_FIRE_TIME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_STATE }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST_MISFIRE_GRP = Internal.createIndex("IDX_QRTZ_T_NFT_ST_MISFIRE_GRP", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.MISFIRE_INSTR, QrtzTriggers.QRTZ_TRIGGERS.NEXT_FIRE_TIME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_GROUP, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_STATE }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_N_G_STATE = Internal.createIndex("IDX_QRTZ_T_N_G_STATE", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_GROUP, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_STATE }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_N_STATE = Internal.createIndex("IDX_QRTZ_T_N_STATE", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_GROUP, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_STATE }, false);
        public static Index QRTZ_TRIGGERS_IDX_QRTZ_T_STATE = Internal.createIndex("IDX_QRTZ_T_STATE", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_STATE }, false);
        public static Index QRTZ_TRIGGERS_PRIMARY = Internal.createIndex("PRIMARY", QrtzTriggers.QRTZ_TRIGGERS, new OrderField[] { QrtzTriggers.QRTZ_TRIGGERS.SCHED_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_NAME, QrtzTriggers.QRTZ_TRIGGERS.TRIGGER_GROUP }, true);
        public static Index SCHOOL_PRIMARY = Internal.createIndex("PRIMARY", School.SCHOOL, new OrderField[] { School.SCHOOL.ID }, true);
    }
}
