/*
 * This file is generated by jOOQ.
*/
package alex.jooq;


import alex.jooq.tables.Customer;
import alex.jooq.tables.Person;
import alex.jooq.tables.QrtzBlobTriggers;
import alex.jooq.tables.QrtzCalendars;
import alex.jooq.tables.QrtzCronTriggers;
import alex.jooq.tables.QrtzFiredTriggers;
import alex.jooq.tables.QrtzJobDetails;
import alex.jooq.tables.QrtzLocks;
import alex.jooq.tables.QrtzPausedTriggerGrps;
import alex.jooq.tables.QrtzSchedulerState;
import alex.jooq.tables.QrtzSimpleTriggers;
import alex.jooq.tables.QrtzSimpropTriggers;
import alex.jooq.tables.QrtzTriggers;
import alex.jooq.tables.School;
import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>test.person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>test.qrtz_blob_triggers</code>.
     */
    public static final QrtzBlobTriggers QRTZ_BLOB_TRIGGERS = QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS;

    /**
     * The table <code>test.qrtz_calendars</code>.
     */
    public static final QrtzCalendars QRTZ_CALENDARS = QrtzCalendars.QRTZ_CALENDARS;

    /**
     * The table <code>test.qrtz_cron_triggers</code>.
     */
    public static final QrtzCronTriggers QRTZ_CRON_TRIGGERS = QrtzCronTriggers.QRTZ_CRON_TRIGGERS;

    /**
     * The table <code>test.qrtz_fired_triggers</code>.
     */
    public static final QrtzFiredTriggers QRTZ_FIRED_TRIGGERS = QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS;

    /**
     * The table <code>test.qrtz_job_details</code>.
     */
    public static final QrtzJobDetails QRTZ_JOB_DETAILS = QrtzJobDetails.QRTZ_JOB_DETAILS;

    /**
     * The table <code>test.qrtz_locks</code>.
     */
    public static final QrtzLocks QRTZ_LOCKS = QrtzLocks.QRTZ_LOCKS;

    /**
     * The table <code>test.qrtz_paused_trigger_grps</code>.
     */
    public static final QrtzPausedTriggerGrps QRTZ_PAUSED_TRIGGER_GRPS = QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS;

    /**
     * The table <code>test.qrtz_scheduler_state</code>.
     */
    public static final QrtzSchedulerState QRTZ_SCHEDULER_STATE = QrtzSchedulerState.QRTZ_SCHEDULER_STATE;

    /**
     * The table <code>test.qrtz_simple_triggers</code>.
     */
    public static final QrtzSimpleTriggers QRTZ_SIMPLE_TRIGGERS = QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS;

    /**
     * The table <code>test.qrtz_simprop_triggers</code>.
     */
    public static final QrtzSimpropTriggers QRTZ_SIMPROP_TRIGGERS = QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS;

    /**
     * The table <code>test.qrtz_triggers</code>.
     */
    public static final QrtzTriggers QRTZ_TRIGGERS = QrtzTriggers.QRTZ_TRIGGERS;

    /**
     * The table <code>test.school</code>.
     */
    public static final School SCHOOL = School.SCHOOL;
}
