package alex.dao;

import alex.dto.School;

public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int insert(School row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int insertSelective(School row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    School selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int updateByPrimaryKeySelective(School row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int updateByPrimaryKey(School row);
}