debug: false
server:
  port: 443
  ssl:
    key-store: classpath:keystore.jks
    key-alias: localhost-root
    key-store-type: JKS
    key-store-password: finance
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true