package alex.dao;

import alex.dto.Person;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int insert(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int insertSelective(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int updateByPrimaryKeySelective(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Nov 27 23:50:17 GST 2023
     */
    int updateByPrimaryKey(Person row);
}