package alex.dto;

public class Person {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column person.id
     *
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column person.name
     *
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column person.address
     *
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column person.age
     *
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column person.id
     *
     * @return the value of person.id
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table person
     *
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public Person withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column person.name
     *
     * @return the value of person.name
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table person
     *
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public Person withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * person.address
     *
     * @return the value of person.address
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column person.address
     *
     * @param address the value for person.address
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table person
     *
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public Person withAddress(String address) {
        this.setAddress(address);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column person.age
     *
     * @return the value of person.age
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column person.age
     *
     * @param age the value for person.age
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table person
     *
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    public Person withAge(Integer age) {
        this.setAge(age);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table person
     *
     * @mbg.generated Fri Oct 06 09:41:17 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", address=").append(address);
        sb.append(", age=").append(age);
        sb.append("]");
        return sb.toString();
    }
}